knp_paginator:
    page_range: 5          # nombre de pages visibles autour de la page active
    default_options:
        page_name: page    # nom du paramètre GET
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap5_v5_pagination.html.twig'
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'
